### ISSUE TITLE
Adding a file to $PATH?

### ISSUE THREAD

**Issue by unixorn** [hsrzq/PluginForTailscale#1]
On my MBP, `/Applications/Tailscale.app/Contents/MacOS/Tailscale` is a binary, not a directory.

Also consider wrapping it in a 
```sh
if [[ "$(uname -s)" = "Darwin" ]]; then
...
fi
```

block so it only gets used on macOS

**Comment by hsrzq** [comment]
Thank you so much! I've fixed it.
